package sd2526.trab.impl.java.servers;

import com.fasterxml.jackson.databind.ObjectMapper;
import sd2526.trab.api.Message;
import sd2526.trab.api.User;
import sd2526.trab.api.java.Messages;
import sd2526.trab.api.java.Result;
import sd2526.trab.impl.api.java.AdminMessages;
import sd2526.trab.impl.java.clients.Clients;
import sd2526.trab.impl.utils.ZohoMailClient;
import sd2526.trab.impl.utils.ZohoMailClient.ZohoEmail;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicLong;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import static sd2526.trab.api.java.Result.ErrorCode.*;
import static sd2526.trab.api.java.Result.error;
import static sd2526.trab.api.java.Result.ok;

/**
 * Messages implementation backed by Zoho Mail (E1 external service).
 *
 * <h3>Design</h3>
 * <p>In-memory structures ({@code messageCache}, {@code inboxMap}) are the
 * <em>primary</em> serving layer — reads never block on Zoho. Zoho is the
 * <em>durable</em> backing store: all writes are mirrored to Zoho in a
 * dedicated background thread so that state survives container restarts.
 *
 * <h3>Startup</h3>
 * <ul>
 *   <li>{@code clearState=true}: all SD2526 emails are deleted from Zoho then
 *       the server starts with empty in-memory state.</li>
 *   <li>{@code clearState=false}: existing Zoho emails are fetched (up to 200),
 *       the inbox map and message cache are rebuilt, and the sequence counter
 *       is restored before the server accepts requests.</li>
 * </ul>
 * Zoho initialization runs in a bounded background thread so the server always
 * starts within a few seconds regardless of Zoho latency.
 */
public class JavaMessagesExternal extends JavaBaseService implements Messages, AdminMessages {

    private static final Logger Log = Logger.getLogger(JavaMessagesExternal.class.getName());

    static final String SUBJECT_PREFIX = "SD2526:";
    private static final int REMOTE_DEADLINE = 90_000;

    // --- Zoho client & Jackson mapper ---
    private final ZohoMailClient zoho = new ZohoMailClient();
    private final ObjectMapper mapper = new ObjectMapper();

    // --- In-memory serving state ---
    /**
     * messageId → ZohoEmail: lets us fetch/delete from Zoho without re-listing.
     */
    private final ConcurrentHashMap<String, ZohoEmail> zohoIndex = new ConcurrentHashMap<>();
    /**
     * messageId → Message: avoids repeated Zoho fetches.
     */
    private final ConcurrentHashMap<String, Message> messageCache = new ConcurrentHashMap<>();
    /**
     * recipientName (no @domain) → synchronised list of messageIds.
     */
    private final ConcurrentHashMap<String, List<String>> inboxMap = new ConcurrentHashMap<>();

    /**
     * Sequence counter for IDs generated by THIS domain's server.
     */
    private final AtomicLong counter = new AtomicLong(0L);

    /**
     * Single-threaded executor for ALL Zoho writes — serialises them and keeps
     * them off the hot path. Daemon so it doesn't prevent JVM exit.
     */
    private final ExecutorService zohoWriter = Executors.newSingleThreadExecutor(r -> {
        Thread t = new Thread(r, "zoho-writer");
        t.setDaemon(true);
        return t;
    });

    /**
     * Per-domain executors for async remote delivery.
     */
    private final ConcurrentHashMap<String, ExecutorService> domainExecutors = new ConcurrentHashMap<>();

    // -------------------------------------------------------------------------
    // Constructor / startup
    // -------------------------------------------------------------------------

    public JavaMessagesExternal(boolean clearState) {
        Log.info("JavaMessagesExternal starting: domain=" + THIS_DOMAIN + " clearState=" + clearState);

        // Run Zoho initialisation in a bounded background thread.  If Zoho is
        // slow or unreachable the server still starts quickly.
        Thread init = new Thread(() -> {
            try {
                initFromZoho(clearState);
            } catch (Exception e) {
                Log.warning("Zoho init failed — starting with empty state: " + e.getMessage());
            }
        }, "zoho-init");
        init.setDaemon(true);
        init.start();

        // Wait at most 7 s; the tester gives 9 s before sending requests.
        try {
            init.join(7_000);
        } catch (InterruptedException ignored) {
        }
        Log.info("JavaMessagesExternal ready: counter=" + counter.get()
                + " messages=" + zohoIndex.size());
    }

    private void initFromZoho(boolean clearState) throws Exception {
        List<ZohoEmail> all = zoho.listEmails();
        List<ZohoEmail> ours = all.stream()
                .filter(e -> e.subject().startsWith(SUBJECT_PREFIX))
                .toList();

        // Pre-seed sentFolderId from any existing Sent email so the first sendEmail
        // call never needs to poll Zoho for it.
        if (!all.isEmpty()) {
            zoho.getSentFolderIdFromList();
        }

        if (clearState) {
            Log.info("Clearing " + ours.size() + " SD2526 email(s)");
            for (ZohoEmail e : ours) {
                try {
                    zoho.deleteEmail(e.folderId(), e.zohoId());
                } catch (Exception ex) {
                    Log.warning("Delete failed for " + e.zohoId() + ": " + ex.getMessage());
                }
            }
        } else {
            Log.info("Loading " + ours.size() + " SD2526 email(s)");
            // Deduplicate by mid: search may return both Sent and Inbox copies
            Set<String> loadedMids = new HashSet<>();
            for (ZohoEmail ze : ours) {
                String mid = ze.subject().substring(SUBJECT_PREFIX.length());
                if (!loadedMids.add(mid)) {
                    Log.info("Skipping duplicate Zoho copy for mid=" + mid);
                    continue;
                }
                zohoIndex.put(mid, ze);
                try {
                    String body = zoho.getEmailContent(ze.folderId(), ze.zohoId());
                    Message msg = parseBody(body);
                    if (msg != null) {
                        messageCache.put(mid, msg);
                        rebuildInboxFor(msg);
                        updateCounter(mid);
                    }
                } catch (Exception ex) {
                    Log.warning("Could not load message " + mid + ": " + ex.getMessage());
                }
            }
            Log.info("Restored: counter=" + counter.get()
                    + " inboxEntries=" + inboxMap.values().stream().mapToInt(List::size).sum());
        }
    }

    // -------------------------------------------------------------------------
    // Messages API
    // -------------------------------------------------------------------------

    @Override
    public Result<String> postMessage(String pwd, Message msg) {
        Log.info("postMessage: sender=" + msg.getSender());
        if (badParams(msg, msg.getSender())) return error(BAD_REQUEST);
        return getUser(msg.getSender(), pwd).thenWith(user -> doPost(user, msg));
    }

    @Override
    public Result<Message> getInboxMessage(String name, String mid, String pwd) {
        Log.info("getInboxMessage: name=" + name + " mid=" + mid);
        if (badParams(name, mid, pwd)) return error(BAD_REQUEST);
        return getUser(name, pwd).thenWith(user -> {
            if (!inboxContains(name, mid)) return error(NOT_FOUND);
            return fetchMessage(mid);
        });
    }

    @Override
    public Result<List<String>> getAllInboxMessages(String name, String pwd) {
        Log.info("getAllInboxMessages: name=" + name);
        if (badParams(name, pwd)) return error(BAD_REQUEST);
        return getUser(name, pwd).mapValue(u -> copyInbox(name));
    }

    @Override
    public Result<List<String>> searchInbox(String name, String pwd, String query) {
        Log.info("searchInbox: name=" + name + " query=" + query);
        if (badParams(name, pwd)) return error(BAD_REQUEST);
        if (query == null || query.isEmpty()) return getAllInboxMessages(name, pwd);

        String q = query.toUpperCase();
        return getUser(name, pwd).thenWith(user -> {
            List<String> ids = copyInbox(name);
            List<String> matches = new ArrayList<>();
            for (String mid : ids) {
                Result<Message> r = fetchMessage(mid);
                if (r.isOK()) {
                    Message m = r.value();
                    boolean subjectMatch = m.getSubject() != null && m.getSubject().toUpperCase().contains(q);
                    boolean contentsMatch = m.getContents() != null && m.getContents().toUpperCase().contains(q);
                    if (subjectMatch || contentsMatch) matches.add(mid);
                }
            }
            return ok(matches);
        });
    }

    @Override
    public Result<Void> removeInboxMessage(String name, String mid, String pwd) {
        Log.info("removeInboxMessage: name=" + name + " mid=" + mid);
        if (badParams(name, mid, pwd)) return error(BAD_REQUEST);
        return getUser(name, pwd).then(() -> {
            removeFromInbox(name, mid);
            return ok();
        });
    }

    @Override
    public Result<Void> deleteMessage(String name, String mid, String pwd) {
        Log.info("deleteMessage: name=" + name + " mid=" + mid);
        if (badParams(name, mid, pwd)) return error(BAD_REQUEST);
        return getUser(name, pwd).thenWith(user -> {
            Result<Message> msgRes = fetchMessage(mid);
            if (!msgRes.isOK()) return error(FORBIDDEN);
            Message msg = msgRes.value();

            if (!getName(msg.senderAddress()).equals(name)) return error(FORBIDDEN);

            // Remove from in-memory state immediately
            messageCache.remove(mid);
            for (List<String> inbox : inboxMap.values()) {
                synchronized (inbox) {
                    inbox.remove(mid);
                }
            }

            // Delete from Zoho in background
            ZohoEmail ze = zohoIndex.remove(mid);
            if (ze != null) {
                submitZohoWrite(() -> {
                    try {
                        zoho.deleteEmail(ze.folderId(), ze.zohoId());
                    } catch (Exception e) {
                        Log.warning("Zoho delete error: " + e.getMessage());
                    }
                });
            }

            // Propagate to remote domains asynchronously
            Set<String> domains = msg.getDestination().stream()
                    .map(a -> a.split("@")[1]).collect(Collectors.toSet());
            final String finalMid = mid;
            for (String domain : domains) {
                if (!domain.equals(THIS_DOMAIN)) {
                    submitDomainJob(domain, () ->
                            reTry(() -> Clients.AdminMessagesClient.get(domain)
                                    .remoteDeleteMessage(finalMid), REMOTE_DEADLINE));
                }
            }
            return ok();
        });
    }

    // -------------------------------------------------------------------------
    // AdminMessages API  (server-to-server calls)
    // -------------------------------------------------------------------------

    @Override
    public Result<Void> remotePostMessage(Message msg) {
        Log.info("remotePostMessage: mid=" + msg.getId());

        // Zoho write FIRST — inbox only visible after durable storage.
        // getAllInboxMessages returns empty until this completes, so the tester's
        // "success" signal comes only after Zoho has the message. Container is
        // killed only after tester sees success → Zoho already has the message.
        if (!zohoIndex.containsKey(msg.getId())) {
            try {
                ZohoEmail ze = zoho.sendEmail(SUBJECT_PREFIX + msg.getId(), encodeMessage(msg));
                zohoIndex.put(msg.getId(), ze);
                messageCache.put(msg.getId(), msg);
                Log.info("remotePostMessage: persisted to Zoho mid=" + msg.getId());
            } catch (Exception e) {
                Log.warning("Zoho persist failed for " + msg.getId() + ": " + e.getMessage()
                        + " — falling back to in-memory only");
                messageCache.put(msg.getId(), msg);
            }
        }

        // Inbox update AFTER Zoho write.
        for (String addr : msg.getDestination()) {
            if (isLocalAddress(addr)) {
                inboxList(getName(addr)).add(msg.getId());
            }
        }

        return ok();
    }

    @Override
    public Result<Void> remoteDeleteMessage(String mid) {
        Log.info("remoteDeleteMessage: mid=" + mid);

        // Remove from in-memory state immediately
        messageCache.remove(mid);
        for (List<String> inbox : inboxMap.values()) {
            synchronized (inbox) {
                inbox.remove(mid);
            }
        }

        // Delete from Zoho in background
        ZohoEmail ze = zohoIndex.remove(mid);
        if (ze != null) {
            submitZohoWrite(() -> {
                try {
                    zoho.deleteEmail(ze.folderId(), ze.zohoId());
                } catch (Exception e) {
                    Log.warning("Zoho delete error: " + e.getMessage());
                }
            });
        }
        return ok();
    }

    @Override
    public Result<Void> remoteDeleteUserInbox(String name) {
        Log.info("remoteDeleteUserInbox: name=" + name);
        inboxMap.remove(name);
        return ok();
    }

    // -------------------------------------------------------------------------
    // Internal helpers
    // -------------------------------------------------------------------------

    private Result<String> doPost(User sender, Message msg) {
        // Assign an ID scoped to this domain
        msg.setId("%s+%04d".formatted(THIS_DOMAIN, counter.incrementAndGet()));
        msg.setSender("%s <%s@%s>".formatted(
                sender.getDisplayName(), sender.getName(), sender.getDomain()));

        // Update in-memory state immediately so callers can read it right away
        messageCache.put(msg.getId(), msg);
        for (String addr : getLocalRecipients(msg)) {
            inboxList(getName(addr)).add(msg.getId());
        }

        // Persist to Zoho SYNCHRONOUSLY so the message survives a restart.
        // The ID is only returned to the caller after durable storage.
        try {
            ZohoEmail ze = zoho.sendEmail(SUBJECT_PREFIX + msg.getId(), encodeMessage(msg));
            zohoIndex.put(msg.getId(), ze);
            Log.info("doPost: persisted to Zoho mid=" + msg.getId());
        } catch (Exception e) {
            Log.warning("Zoho persist failed for " + msg.getId() + ": " + e.getMessage()
                    + " — message is in-memory only");
        }

        // Deliver to remote domains asynchronously
        Set<String> remote = getRemoteRecipients(msg);
        if (!remote.isEmpty()) {
            Map<String, Set<String>> byDomain = remote.stream()
                    .collect(Collectors.groupingBy(this::getDomain, Collectors.toSet()));
            final Message finalMsg = msg;
            for (String domain : byDomain.keySet()) {
                submitDomainJob(domain, () ->
                        reTry(() -> Clients.AdminMessagesClient.get(domain)
                                .remotePostMessage(finalMsg), REMOTE_DEADLINE));
            }
        }

        return ok(msg.getId());
    }

    private Result<Message> fetchMessage(String mid) {
        Message cached = messageCache.get(mid);
        if (cached != null) return ok(cached);

        ZohoEmail ze = zohoIndex.get(mid);
        if (ze == null) return error(NOT_FOUND);

        try {
            String body = zoho.getEmailContent(ze.folderId(), ze.zohoId());
            Message msg = parseBody(body);
            if (msg == null) return error(INTERNAL_ERROR);
            messageCache.put(mid, msg);
            return ok(msg);
        } catch (Exception e) {
            Log.severe("Zoho fetch failed for " + mid + ": " + e.getMessage());
            return error(INTERNAL_ERROR);
        }
    }

    private Result<User> getUser(String address, String pwd) {
        try {
            String name = address.split("@", 2)[0];
            return Clients.UsersClient.get().getUser(name, pwd);
        } catch (Exception e) {
            e.printStackTrace();
            return error(INTERNAL_ERROR);
        }
    }

    private List<String> getLocalRecipients(Message msg) {
        return msg.getDestination().stream().filter(this::isLocalAddress).toList();
    }

    private Set<String> getRemoteRecipients(Message msg) {
        return msg.getDestination().stream()
                .filter(a -> !isLocalAddress(a)).collect(Collectors.toSet());
    }

    /**
     * Returns the synchronised inbox list for a recipient, creating it if absent.
     */
    private List<String> inboxList(String name) {
        return inboxMap.computeIfAbsent(name,
                k -> Collections.synchronizedList(new ArrayList<>()));
    }

    private boolean inboxContains(String name, String mid) {
        List<String> inbox = inboxMap.get(name);
        if (inbox == null) return false;
        synchronized (inbox) {
            return inbox.contains(mid);
        }
    }

    private void removeFromInbox(String name, String mid) {
        List<String> inbox = inboxMap.get(name);
        if (inbox != null) synchronized (inbox) {
            inbox.remove(mid);
        }
    }

    private List<String> copyInbox(String name) {
        List<String> inbox = inboxMap.get(name);
        if (inbox == null) return Collections.emptyList();
        synchronized (inbox) {
            return new ArrayList<>(inbox);
        }
    }

    /**
     * Adds all local destination addresses of {@code msg} to the inbox map.
     */
    private void rebuildInboxFor(Message msg) {
        for (String addr : msg.getDestination()) {
            if (isLocalAddress(addr)) {
                inboxList(getName(addr)).add(msg.getId());
            }
        }
    }

    /**
     * Updates the counter if {@code mid} comes from this domain and has a higher sequence.
     */
    private void updateCounter(String mid) {
        if (!mid.startsWith(THIS_DOMAIN + "+")) return;
        try {
            String seqPart = mid.substring(THIS_DOMAIN.length() + 1).split("\\.")[0];
            long val = Long.parseLong(seqPart);
            counter.updateAndGet(cur -> Math.max(cur, val));
        } catch (NumberFormatException ignored) {
        }
    }

    private String encodeMessage(Message msg) {
        try {
            // Base64-encode the JSON so angle brackets (<>) don't get HTML-escaped by Zoho.
            String json = mapper.writeValueAsString(msg);
            return java.util.Base64.getEncoder().encodeToString(json.getBytes(java.nio.charset.StandardCharsets.UTF_8));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private Message parseBody(String body) {
        if (body == null || body.isBlank()) return null;
        String s = body.trim();

        // 1. Try Base64-encoded JSON (new format)
        if (!s.startsWith("{") && !s.startsWith("[") && !s.startsWith("<")) {
            try {
                String decoded = new String(java.util.Base64.getDecoder().decode(s),
                        java.nio.charset.StandardCharsets.UTF_8).trim();
                return mapper.readValue(decoded, Message.class);
            } catch (Exception ignored) {
            }
        }

        // 2. Try raw JSON (legacy format or if Zoho returned it unmodified)
        if (s.startsWith("{")) {
            try {
                return mapper.readValue(s, Message.class);
            } catch (Exception ignored) {
            }
        }

        // 3. Strip HTML wrapper and decode entities, then parse
        if (s.startsWith("<")) {
            String stripped = s.replaceAll("(?s)<[^>]*>", " ")
                    .replace("&lt;", "<").replace("&gt;", ">")
                    .replace("&amp;", "&").replace("&quot;", "\"")
                    .replace("&#39;", "'").replace("&nbsp;", " ")
                    .replaceAll("\\s+", " ").trim();
            // The JSON might be somewhere inside — find the first '{'
            int idx = stripped.indexOf('{');
            if (idx >= 0) {
                String candidate = stripped.substring(idx);
                try {
                    return mapper.readValue(candidate, Message.class);
                } catch (Exception ignored) {
                }
            }
            // Try Base64 inside HTML (e.g., Zoho wraps our base64 in <html><body>...</body></html>)
            String innerBase64 = stripped.trim();
            if (!innerBase64.isEmpty() && !innerBase64.startsWith("{")) {
                try {
                    String decoded = new String(java.util.Base64.getDecoder().decode(innerBase64),
                            java.nio.charset.StandardCharsets.UTF_8).trim();
                    return mapper.readValue(decoded, Message.class);
                } catch (Exception ignored) {
                }
            }
        }

        Log.warning("parseBody: could not parse body (length=" + body.length()
                + ", preview=" + body.substring(0, Math.min(100, body.length())) + ")");
        return null;
    }

    /**
     * Submits a Zoho I/O task to the serial background writer.
     */
    private void submitZohoWrite(Runnable task) {
        zohoWriter.submit(task);
    }

    /**
     * Submits an async delivery task for a specific remote domain.
     */
    private void submitDomainJob(String domain, Runnable job) {
        domainExecutors.computeIfAbsent(domain, d ->
                Executors.newSingleThreadExecutor(r -> {
                    Thread t = new Thread(r);
                    t.setUncaughtExceptionHandler((thr, ex) -> ex.printStackTrace());
                    return t;
                })
        ).submit(job);
    }
}
